In [ ]:
pip install numpy

Requirement already satisfied: numpy in c:\users\user\opencv\lib\site-packages (1.19.5)
Note: you may need to restart the kernel to use updated packages.

Import all the libraries needed.

In [1]:
# Import Python Libraries
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import seaborn as sns

Reading data using pandas

In [2]:
# Read CSV file
df = pd.read_csv("HR_Employee_Retention.csv")
print(df.shape)
df.sample(5)

(14999, 10)

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
12348,0.11,0.84,7,264,4,0,1,0,technical,medium
7923,0.98,0.87,5,151,6,0,0,0,IT,medium
6775,0.90,0.64,5,226,2,0,0,0,technical,low
8862,0.25,0.96,6,217,4,0,0,0,marketing,low
14571,0.10,0.87,6,290,4,0,1,0,support,low

In [3]:
df.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

In [ ]:
dir(df)

['T',
 'Work_accident',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_add_numeric_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_from_arguments',
 '_construct_result',
 '_constructor',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_data',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_from_arrays',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_join_compat',
 '_logical_func',
 '_logical_method',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_stat_function',
 '_stat_function_ddof',
 '_take',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'average_montly_hours',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_evaluation',
 'last_valid_index',
 'le',
 'left',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'number_project',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'promotion_last_5years',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'salary',
 'sales',
 'sample',
 'satisfaction_level',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'time_spend_company',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [4]:
#Check aparticular column type
df['number_project'].dtype

dtype('int64')

In [ ]:
#Check types for all the columns
df.dtypes

satisfaction_level       float64
last_evaluation          float64
number_project             int64
average_montly_hours       int64
time_spend_company         int64
Work_accident              int64
left                       int64
promotion_last_5years      int64
sales                     object
salary                    object
dtype: object

In [10]:
df.describe()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years
count,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000
mean,0.612834,0.716102,3.803054,201.050337,3.498233,0.144610,0.238083,0.021268
std,0.248631,0.171169,1.232592,49.943099,1.460136,0.351719,0.425924,0.144281
min,0.090000,0.360000,2.000000,96.000000,2.000000,0.000000,0.000000,0.000000
25%,0.440000,0.560000,3.000000,156.000000,3.000000,0.000000,0.000000,0.000000
50%,0.640000,0.720000,4.000000,200.000000,3.000000,0.000000,0.000000,0.000000
75%,0.820000,0.870000,5.000000,245.000000,4.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,7.000000,310.000000,10.000000,1.000000,1.000000,1.000000

In [ ]:
df.satisfaction_level

0        0.38
1        0.80
2        0.11
3        0.72
4        0.37
         ...
14994    0.40
14995    0.37
14996    0.37
14997    0.11
14998    0.37
Name: satisfaction_level, Length: 14999, dtype: float64

In [11]:
df.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

In [12]:
#Group data using 'left'
df_rank = df.groupby(['left'])
print(df_rank)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7aef02c442b0>

In [13]:
#Calculate mean value for each numeric column per each group
df_rank.mean()

<ipython-input-13-a9a6cf870272>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_rank.mean()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years
left,,,,,,,
0,0.666810,0.715473,3.786664,199.060203,3.380032,0.175009,0.026251
1,0.440098,0.718113,3.855503,207.419210,3.876505,0.047326,0.005321

In [ ]:
# Calculate mean satisfaction level for each 'left' category:
df.groupby('left')[['satisfaction_level']].mean()

      satisfaction_level
left
0               0.666810
1               0.440098

In [ ]:
# Filter data where project_number is greater than 3
df_sub = df[ df['number_project'] > 3 ]

df_sub

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
6,0.10,0.77,6,247,4,0,1,0,sales,low
7,0.92,0.85,5,259,5,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14987,0.90,0.70,5,206,4,0,1,0,technical,low
14990,0.89,0.88,5,228,5,1,1,0,support,low
14991,0.09,0.81,6,257,4,0,1,0,support,low
14993,0.76,0.83,6,293,6,0,1,0,support,low
14997,0.11,0.96,6,280,4,0,1,0,support,low

In [ ]:
#Select only those rows that contain employees who earn low salary
df_sale = df[ df['salary'] == 'low' ]

df_sale

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low
5,0.41,0.50,2,153,3,0,1,0,sales,low
6,0.10,0.77,6,247,4,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14994,0.40,0.57,2,151,3,0,1,0,support,low
14995,0.37,0.48,2,160,3,0,1,0,support,low
14996,0.37,0.53,2,143,3,0,1,0,support,low
14997,0.11,0.96,6,280,4,0,1,0,support,low
14998,0.37,0.52,2,158,3,0,1,0,support,low

In [18]:
# Select column salary:
df[['salary']]

       salary
0         low
1      medium
2      medium
3         low
4         low
...       ...
14994     low
14995     low
14996     low
14997     low
14998     low

[14999 rows x 1 columns]

In [17]:
#Select column sales and salary:
df[['sales','salary']]

         sales  salary
0        sales     low
1        sales  medium
2        sales  medium
3        sales     low
4        sales     low
...        ...     ...
14994  support     low
14995  support     low
14996  support     low
14997  support     low
14998  support     low

[14999 rows x 2 columns]

In [23]:
df[10:20]

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
10,0.45,0.54,2,135,3,0,1,0,sales,low
11,0.11,0.81,6,305,4,0,1,0,sales,low
12,0.84,0.92,4,234,5,0,1,0,sales,low
13,0.41,0.55,2,148,3,0,1,0,sales,low
14,0.36,0.56,2,137,3,0,1,0,sales,low
15,0.38,0.54,2,143,3,0,1,0,sales,low
16,0.45,0.47,2,160,3,0,1,0,sales,low
17,0.78,0.99,4,255,6,0,1,0,sales,low
18,0.45,0.51,2,160,3,1,1,1,sales,low
19,0.76,0.89,5,262,5,0,1,0,sales,low

In [20]:
df.loc[10:20]

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
10,0.45,0.54,2,135,3,0,1,0,sales,low
11,0.11,0.81,6,305,4,0,1,0,sales,low
12,0.84,0.92,4,234,5,0,1,0,sales,low
13,0.41,0.55,2,148,3,0,1,0,sales,low
14,0.36,0.56,2,137,3,0,1,0,sales,low
15,0.38,0.54,2,143,3,0,1,0,sales,low
16,0.45,0.47,2,160,3,0,1,0,sales,low
17,0.78,0.99,4,255,6,0,1,0,sales,low
18,0.45,0.51,2,160,3,1,1,1,sales,low
19,0.76,0.89,5,262,5,0,1,0,sales,low
20,0.11,0.83,6,282,4,0,1,0,sales,low

In [24]:
df.loc[10:20, ['last_evaluation', 'Work_accident']]

    last_evaluation  Work_accident
10             0.54              0
11             0.81              0
12             0.92              0
13             0.55              0
14             0.56              0
15             0.54              0
16             0.47              0
17             0.99              0
18             0.51              1
19             0.89              0
20             0.83              0

In [ ]:
df.iloc[10:20, [1, 5]]

    last_evaluation  Work_accident
10             0.54              0
11             0.81              0
12             0.92              0
13             0.55              0
14             0.56              0
15             0.54              0
16             0.47              0
17             0.99              0
18             0.51              1
19             0.89              0

In [ ]:
#Select rows by their position:
df[10:20]

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
10,0.45,0.54,2,135,3,0,1,0,sales,low
11,0.11,0.81,6,305,4,0,1,0,sales,low
12,0.84,0.92,4,234,5,0,1,0,sales,low
13,0.41,0.55,2,148,3,0,1,0,sales,low
14,0.36,0.56,2,137,3,0,1,0,sales,low
15,0.38,0.54,2,143,3,0,1,0,sales,low
16,0.45,0.47,2,160,3,0,1,0,sales,low
17,0.78,0.99,4,255,6,0,1,0,sales,low
18,0.45,0.51,2,160,3,1,1,1,sales,low
19,0.76,0.89,5,262,5,0,1,0,sales,low

In [ ]:
# Select rows by their labels:
df_sub.loc[10:20,['number_project','satisfaction_level','left']]

    number_project  satisfaction_level  left
11               6                0.11     1
12               4                0.84     1
17               4                0.78     1
19               5                0.76     1
20               6                0.11     1

In [ ]:
#Select rows by their labels (positions):
df_sub.iloc[10:20,[0, 3, 4]]

    satisfaction_level  average_montly_hours  time_spend_company
20                0.11                   282                   4
22                0.09                   304                   4
25                0.89                   242                   5
26                0.82                   239                   5
30                0.09                   294                   4
34                0.84                   246                   6
35                0.10                   255                   4
38                0.11                   306                   4
40                0.87                   269                   5
43                0.10                   281                   4

In [25]:
# Create a new data frame from the original sorted
# by the column 'time_spend_company'
df_sorted = df.sort_values(by ='satisfaction_level')
df_sorted.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
14484,0.09,0.96,6,296,4,0,1,0,technical,low
1873,0.09,0.93,6,279,4,0,1,0,technical,low
340,0.09,0.89,7,308,5,0,1,0,hr,medium
1882,0.09,0.89,6,282,4,0,1,0,support,low
332,0.09,0.98,6,271,4,0,1,0,sales,low

In [ ]:
df_sorted = df.sort_values( by =['time_spend_company', 'number_project'], ascending = [True, False])
df_sorted.head(10)

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
843,0.66,0.47,7,156,2,0,1,0,management,medium
50,0.13,0.78,6,152,2,0,1,0,support,low
710,0.64,0.90,6,252,2,0,1,0,sales,low
1162,0.35,0.80,6,281,2,0,1,0,sales,medium
1925,0.73,0.97,6,189,2,0,1,0,sales,low
2233,0.70,0.89,6,214,2,0,0,0,sales,low
2235,0.15,0.74,6,212,2,0,0,0,sales,low
2279,0.96,0.45,6,232,2,1,0,0,product_mng,low
2386,0.84,0.51,6,141,2,1,0,0,sales,low
2502,0.63,0.61,6,118,2,0,0,0,IT,low

In [ ]:
# Select the rows that have at least one missing value
df[df.isnull().any(axis=1)].head()

Empty DataFrame
Columns: [satisfaction_level, last_evaluation, number_project, average_montly_hours, time_spend_company, Work_accident, left, promotion_last_5years, sales, salary]
Index: []